### ISSUE TITLE
Api call 404

### ISSUE THREAD

**Issue by miguellopes** [ramezrafla/spreed-bigbluebutton#1]
I saw you posting the link on the forum and went straight to installing BBB on a separate machine. I have It working with SSL.
After coping and ativating the app I go back with cache disabled, I get the exact same interface and the call doesn't work.
I'm getting a 404 on a POST to ocs/v2.php/apps/spreed/api/v1/call/2kocwkvs with {"flags":1}

I'm not seeing anything else that seems wrong. except I don't see the browser connecting to the bbb host.

Thanks for sharing

**Comment by miguellopes** [comment]
I don't seem to be able to activate the module.. It shows the Talk tab but every time I click to enable and refresh the page it asks again to enable. Never touched a NC app before today so I'm not sure if it's relevant.

**Comment by ramezrafla** [comment]
Hi @miguellopes 

Do you see an iframe loading?

If not you are still using the old Talk? You need to completely remove from /apps and reload your page (incognito to be sure)

**Comment by miguellopes** [comment]
Hi,
I have no iframe, I disable the app on the dashboard deleted the folder /data/spreed a cloned the repo on the stable branch. Used different browsers to the same end. The Iframe points to the domain of bbb right?
I don't see the Iframe anywhere, is it supposed to show up on the source of the page or is it loaded on runtime?

Thanks

**Comment by ramezrafla** [comment]
Do you have a BBB server setup? Did you add its parameters to your config.php? 

Please do another pull of latest version, we made a few additions to support missing setup in config.php (fails gracefully now)

**Comment by miguellopes** [comment]
Just did a pull opened in incognito and still the same. yes at the end before the last ");" I added the server.
I noticed that the url I added is returning 404, on /bigbluebutton/ I have it on root, even after removing that part still doesn't work I only get the same UI I had before.

**Comment by ramezrafla** [comment]
So your BBB server does not work. That's the basis of the whole thing!

When you call your BBB sever with `/bigbluebutton/` or `/bigbluebutton/api` you should get

```
<response>
  <script/>
  <returncode>SUCCESS</returncode>
  <version>2.0</version>
</response>
```

I am going to close this issue unless you see something wrong with this App.

[Updating troubleshooting in Readme]

**Comment by miguellopes** [comment]
are the api demos required?

**Comment by ramezrafla** [comment]
I would say yes, to test it out first to make BBB server is working, then remove in production.

Feel free to open an issue if you have problems with the App.
