### ISSUE TITLE
Join call on iOS not working (401)

### ISSUE THREAD

**Issue by remmedia** [ramezrafla/spreed-bigbluebutton#11]
## Steps to reproduce
Join call on iOS as registered User or via Guest Link does not work

### Expected behaviour
Tell us what should happen

### Actual behaviour
Error 401 - session XXX not found (on bbb server)

## Browser
**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
ios
**Browser name:** Firefox/Chrome/...
Safari
**Browser version:** 50.1/55/...

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
8.0.8
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
no
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
no

## Server configuration

**Operating system**: Ubuntu/RedHat/...
debian
**Web server:** Apache/Nginx
apache
**Database:** MySQL/Maria/SQLite/PostgreSQL
mariadb
**PHP version:**
7.4
**Nextcloud Version:** (see admin page)
18.0.4

**Comment by ramezrafla** [comment]
Hi @remmedia 

I have been using this fork on my iOS device (and so have clients) with no issues
Can you repull the repo and try again? There have been some fixes recently that may have affected your case (depending on when you started using)

But note that we are talking about the **browser** on iOS, not the Talk mobile app. This fork is not compatible with the original Talk app.
