### ISSUE TITLE
Full Screen in presentation breaks in IFrame

### ISSUE THREAD

**Issue by codegeek1001** [ramezrafla/spreed-bigbluebutton#12]
**Is your feature request related to a problem? Please describe.**
In Iframe, the fullscreen icon for presentation does not work. This is due to the iframe permissions not set by default.

**Describe the solution you'd like**
Ideally, we should add this attribute/parameter "allowfullscreen" for iframe parameters.  

    <iframe allowfullscreen........

**Comment by ramezrafla** [comment]
@codegeek1001 
Are you sure? Did you pull the latest version of stable18-bbb?
I added `allowfullscreen` already and it's working on my side

**Comment by codegeek1001** [comment]
Yea sorry please ignore. I thought I was logging this in main bigbluebutton issues forum. My bad. you can close this.
