### ISSUE TITLE
Polishing of documentation and publishing to Nextcloud App Store?

### ISSUE THREAD

**Issue by e-alfred** [ramezrafla/spreed-bigbluebutton#2]
Hello,

this looks like an interesting alternative to Nextcloud Talk, do you think the documentation can be polished and a release can be published to the Nextcloud App Store?

**Comment by ramezrafla** [comment]
Agreed -- I add you as a contributor :)

**Comment by menelic** [comment]
Frank @karlitschek  founder of Nextcloud has pledged help in publishing this to the app store: https://help.nextcloud.com/t/nextcloud-app-for-bigbluebutton-integration/74910/72?

Users need to let Nextcloud know that they should prioritise this....

**Comment by ramezrafla** [comment]
We have shelved this development from our side, and the work needed to migrate from original Talk namespaces is huge. I don't see how it can be done without substantial development work.

If someone is interested in taking on, please speak up.

Thanks
