### ISSUE TITLE
Overlayed full screen (spreed) and properties (bbb) button

### ISSUE THREAD

**Issue by avosskuehler** [ramezrafla/spreed-bigbluebutton#3]
First: Thanks for your work!
Im facing the problem not beeing able to click on the Settings Button for BBB at the top right corner after starting the Conference. (Three small dots aligned vertically)
It is overlayed with the full screen button of spreed and (if I close it) the button to show the sidebar with the nextcloud chat.
So I am not able to allow the desktop screen sharing.
I am interested in an workaround or a fix.
## Browser
Firefox
**Microphone available:** yes
**Camera available:** yes
**Operating system:** Windows
**Browser name:** Firefox
**Browser version:** 75

## Talk app
Talk app version: 8.0.7
Custom TURN server configured: no
Custom STUN server configured: no

Kind regards, Adrian

**Comment by avosskuehler** [comment]
As far as I can see it would be enough to move the properties icon of the iframe into the navbar>top>left DIV and change the dropdowns css style from bottom-right to bottom-left.

**Comment by ramezrafla** [comment]
Sorry @avosskuehler 
Yes, that is a bug. It's on my todo to fix.

I am not sure if it should be done in the BBB client or within this app.

**Comment by avosskuehler** [comment]
Hi @ramezrafla, thanks for your reply and the fix on issue #4 (it would be kind, if you also commit the newly compiled js files, cause the makefile does not run on my centos7 system with recent npm and node.js and I have not enough experience to fix it). I would suggest to either remove the imported toggleFullscreen and openSidebar buttons in TopBar.vue cause fullscreen can be achieve via the currently hidden properties button and the nextcloud chat sidebar on the right is a duplicate to the BBB chat on the left. I think even better would be the solution described in my first comment to move the properties button to the left side beneath the showChatInSidebar button.

**Comment by ramezrafla** [comment]
Hi @avosskuehler 

Sorry about not pushing compiled JS, oversight. The original .gitignore excludes them. Doing it asap.

I agree that we need to remove the fullscreen icon. In terms of right side chat vs BBB chat, the latter is temporary and is cleared after the call is over. That Talk chat is nice as it preserves history, notes, connection history etc

**Comment by ramezrafla** [comment]
@avosskuehler 
Rebuilt JS and pushed. Can you give it a spin?

Note: Icons issue not addressed yet

Thanks

**Comment by avosskuehler** [comment]
Thanks @ramezrafla adding the compiled JS. It works fine with the screensharing now.
I agree with the option that the Talk chat on the right side should be available during the call, so best would be to move the bbb properties button to the left... but fear that this is in the bbb code, have not enough insight yet.

**Comment by ramezrafla** [comment]
@avosskuehler 
Can you look at the new UI and let me know if it works better.
BTW, the options button for BBB is not that useful. I was thinking of properly hiding it under the buttons of Talk.

**Comment by avosskuehler** [comment]
Hi @ramezrafla . The new UI just hides the fullscreen button. The BBB properties button is still unclickable (hidden under the stop call button, or the show right sidebar button (when it is closed)). I would recommend not to hide any button, but in fact have all buttons visible and clickable ...

**Comment by ramezrafla** [comment]
@avosskuehler 
We removed the full screen button altogether as the BBB client allows you to fullscreen any view you want (including screen share, videos, slides being presented etc.)

The properties button for BBB is not that useful to be honest. And if you open up the settings page it clashes with overlaid Talk buttons. So am not sure how to handle this.

In my ideal world, I would work on the BBB client too to harmonise, but don't have the time (it means something else to maintain) and it complicates integration by the community.

Short answer: Not an easy call.
