### ISSUE TITLE
Screensharing does not work in Firefox 75 using IFrame

### ISSUE THREAD

**Issue by avosskuehler** [ramezrafla/spreed-bigbluebutton#4]
When clicking on the screenshare I get the message "Error: Permission to access screen wasn´t granted". 
Referring to [https://github.com/bigbluebutton/bigbluebutton/issues/8846] this is due to the missing property allow="display-capture" in the iframe. 
Change it in talk.js and find and replace:
attrs:{allow:"geolocation; microphone; camera;"
with
attrs:{allow:"geolocation; microphone; camera; display-capture;"
and it works.

**Comment by ramezrafla** [comment]
Ok, will make the change and push

**Comment by ramezrafla** [comment]
Done - please repull
