### ISSUE TITLE
Firefox and Safari work, chrome&chromium don't. Cookie policy ???

### ISSUE THREAD

**Issue by joergmschulz** [ramezrafla/spreed-bigbluebutton#5]
## Steps to reproduce
1. while the BBB integration into my nc works perfectly using Firefox or Safari, it doesn't in Chrome.

### Expected behaviour
conference should open
### Actual behaviour

401 error pops up, Session XXXX not found.
The browser console in Chrome/Chromium tells me:
A cookie associated with a cross-site resource at http://conference.blablabla.de/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Just found the cookie storage buckets in Safari and Chrome: Where Safari has a JSESSIONID, Chrome/Chromium do not have them.

So the question seems to be: how to allow those cookies in Chrome, or how to correctly flag the cookies in the BBB server?

**Operating system:** OSX

**Browser name:** Firefox/Chrome/...

**Browser version:** 
chromium: Version 80.0.3987.163 (Entwickler-Build) (64-Bit)
Chrome: Version 80.0.3987.163 (Offizieller Build) (64-Bit)

--- 
this https://community.esri.com/servlet/JiveServlet/showImage/2-907774-480902/pastedImage_1.png helps, but that's not a solution for normal people

**Comment by joergmschulz** [comment]
if the TLD domain names of nextcloud and BBB are the same, it works

**Comment by ramezrafla** [comment]
@joergmschulz 
Sorry for delay. We use with same TLD domains names. Do you have an idea what we should do at our end to resolve this? Extra params to iframe or send a header of some sorts?

**Comment by joergmschulz** [comment]
Re: Delay: all is good. Late and qualified answer is better than none at all. Maybe, I'm no expert on that, it would help to send the session ID cookies with the samesite and secure options. But, probably, this must be done from BBB and not the client app, because this cookie comes from BBB originally.

**Comment by ramezrafla** [comment]
Agreed - I don’t think it’s something we control at our end. Maybe you can have multiple server names on your BBB server and have a new subdomain on the same TLD as your NC instance.

**Comment by joergmschulz** [comment]
Not under control of this app - must tidy up my domain names. Created a PR on the readme on this topic, maybe that helps
