### ISSUE TITLE
No Screensharing in Chrome and Firefox

### ISSUE THREAD

**Issue by Ludovicis** [ramezrafla/spreed-bigbluebutton#6]
Hello, 
Thanks for your app.
On Version 80.0.3987.163 (Build officiel) (64 bits) and Firefox 75.0 (64 bits) no screensharing with Talk (No  screensharing icon), but if i use greenlight no problem.

**Comment by ramezrafla** [comment]
Hello @Ludovicis 
Sorry for delay
This is a BBB client issue. 
Are you the host? If not, the host has to allow you to share your screen

**Comment by ramezrafla** [comment]
We just did a push with a change in iframe attrs as per #4 
Can you pull and retry?
Thanks

**Comment by Ludovicis** [comment]
Hello @ramezrafla,

Thanks, 
I try again and everything is ok for firefox, I tell you again for Chrome a little later.
